export const NIGERIA_STATE_CITIES: Record<string, string[]> = {
  Abia: ["Umuahia", "Aba", "Ohafia"],
  Adamawa: ["Yola", "Mubi", "Numan"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Azare", "Misau"],
  Bayelsa: ["Yenagoa", "Brass", "Sagbama"],
  Benue: ["Makurdi", "Gboko", "Otukpo"],
  Borno: ["Maiduguri", "Biu", "Bama"],
  "Cross River": ["Calabar", "Ikom", "Ogoja"],
  Delta: ["Asaba", "Warri", "Sapele"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke"],
  Edo: ["Benin City", "Ekpoma", "Auchi"],
  Ekiti: ["Ado Ekiti", "Ikere", "Ikole"],
  Enugu: ["Enugu", "Nsukka", "Oji River"],
  FCT: ["Abuja", "Gwarinpa", "Wuse", "Maitama", "Kubwa", "Lugbe"],
  Gombe: ["Gombe", "Kaltungo", "Dukku"],
  Imo: ["Owerri", "Orlu", "Okigwe"],
  Jigawa: ["Dutse", "Hadejia", "Gumel"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Wudil", "Bichi"],
  Katsina: ["Katsina", "Daura", "Funtua"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri"],
  Kogi: ["Lokoja", "Okene", "Kabba"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran"],
  Lagos: ["Ikeja", "Lekki", "Victoria Island", "Yaba", "Surulere", "Ajah"],
  Nassarawa: ["Lafia", "Keffi", "Akwanga"],
  Niger: ["Minna", "Bida", "Suleja"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu"],
  Ondo: ["Akure", "Ondo", "Owo"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo"],
  Plateau: ["Jos", "Bukuru", "Pankshin"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno"],
  Taraba: ["Jalingo", "Wukari", "Bali"],
  Yobe: ["Damaturu", "Potiskum", "Nguru"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara"],
};

export const NIGERIA_STATES = Object.keys(NIGERIA_STATE_CITIES);

export const getCitiesForState = (state: string) =>
  NIGERIA_STATE_CITIES[state] ?? [];
